language: node_js
node_js:
  - 'v19.8.1'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - main

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 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 # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target-branch: gh-pages
  local-dir: .output/public
  on:
    branch: main